#pragma once

#include <string>
#include <map>
#include <vector>
#include <tuple>

#include "LotusLib/Enums.h"
#include "LotusLib/Exceptions.h"

namespace LotusLib
{
    enum class FileType
    {
        UNKNOWN,
        ANIMATION,
        AUDIO_OLD,
        AUDIO,
        BINK2,
        ICON,
        LANDSCAPE,
        LEVEL,
        LEVEL_STATIC,
        LEVEL_T,
        MATERIAL,
        MATERIAL_HLM,
        MODEL_STATIC,
        MODEL_LEVEL1,
        MODEL_LEVEL2,
        MODEL_TERRAIN,
        MODEL_RIGGED,
        MODEL_PACKED,
        MODEL_SM,
        MODEL_DCM_HLOD,
        SHADER,
        SWF,
        TEXTURE_1,
        TEXTURE_2,
        TEXTURE_3,
        TEXTURE_ROUGHNESS,
        TEXTURE_LIGHTMAP_1,
        TEXTURE_SKYBOX,
        TEXTURE_POSTPROCESS,
        TEXTURE_CUBEMAP_1,
        TEXTURE_CUBEMAP_2,
        TEXTURE_CUBEMAP_PARTIAL,
        TEXTURE_NORMALMAP,
        TEXTURE_PACKMAP,
        TEXTURE_LANDSCAPE,
        TEXTURE_DETAILSPACK,
        TEXTURE_FVL,
        TEXTURE_VRGB,
        TEXTURE_ARRAY,
        LIGHTMAP_1,
        LIGHTMAP_2,
        LIGHTMAP_3,
        LIGHTMAP_CUBEMAP_PARTIAL,
        LIGHTMAP_CUBEMAP_SM,
        LIGHTMAP_FVL,
        LIGHTMAP_VRGB,
        LIGHTMAP_HDR,
        VERTEXCOLOR,
    };

    // For each game, define a list of files which upon reading their format enumeration, can be used as reference to map the FileType to an enumeration value, valid only for the current cache.
    // Ex. For WARFRAME, MODEL_RIGGED, PackageCategory::MISC, "/Lotus/Characters/Tenno/Excalibur/Excalibur_skel.fbx"
    //   Reading the file Excalibur_skel.fbx in the MISC package category returns the file enumeration 282.
    //   We can now assume that in this cache, every file format found in a package of category MISC of value 282 is MODEL_RIGGED.
    // All of these paths must ALWAYS EXIST in EVERY VERSION of the specified game. If a file gets removed in the future, assume the file type no longer exists.
    // Why is this called a candle?
    //   By assuming these files always exist and are consistent with their file type, we can use them to determine other file types.
    //   https://en.wikipedia.org/wiki/Cosmic_distance_ladder#Standard_candles
    const std::map<LotusLib::Game, std::vector<std::tuple<FileType, PackageCategory, std::string>>> FILE_CANDLES {
        {
            // These require further investigation.
            // Purely guessing with these.
            Game::DARKSECTOR,
            {
                {FileType::AUDIO, PackageCategory::MISC, "/Music/KeithPower/Ambient3EDIT.wav.1"},
                {FileType::ICON, PackageCategory::MISC, "/Editor/Toolbars/PreviewBoxOrSphere.ico.1"},
                {FileType::LEVEL, PackageCategory::SCENE, "/Levels/Mission05/Start.scene.1"},
                {FileType::MODEL_STATIC, PackageCategory::MISC, "/Environments/Residential/Slums/Objects/Interior/TV.lwo.1"},
                {FileType::MODEL_RIGGED, PackageCategory::MISC, "/Weapons/Machete/Machete_skel.x.1"},
                {FileType::SHADER, PackageCategory::SHADER, "/Materials/Shaders/Rain.shd.1"},
                {FileType::TEXTURE_1, PackageCategory::TEXTURE, "/Levels/MP/Graveyard/Graveyard_0_0_lit.png.1"},
            }
        },
        {
            Game::DARKNESSII,
            {
                {FileType::ANIMATION, PackageCategory::MISC, "/D2/Animations/MPBoss/TurnRight25_anim.fbx"},
                {FileType::AUDIO_OLD, PackageCategory::MISC, "/D2/Music/LicensedMusic/CatherineWheelWaydownCredits"},
                {FileType::AUDIO, PackageCategory::MISC, "/D2/Music/DustinCrenna/HorrorOrganA.wav"},
                {FileType::LEVEL, PackageCategory::ANIM_RETARGET, "/D2/Levels/Hell/Hell/HUBArt_lyr.level"},
                {FileType::MATERIAL, PackageCategory::MISC, "/D2/Weapons/Upgrades/LaserPointer"},
                {FileType::MODEL_STATIC, PackageCategory::MISC, "/D2/Weapons/Syphon/SyphonDoor.fbx"},
                {FileType::MODEL_LEVEL1, PackageCategory::MISC, "/D2/Levels/Hell/Hell/1_c.fbx"},
                {FileType::MODEL_TERRAIN, PackageCategory::MISC, "/D2/Levels/Poker/Poker/Terrain4.tmesh"},
                {FileType::MODEL_RIGGED, PackageCategory::MISC, "/D2/Objects/Vehicles/Taxi/Taxi_skel.fbx"},
                {FileType::SWF, PackageCategory::ANIM_RETARGET, "/EE/Menus/MainMenu.swf"},
                {FileType::TEXTURE_1, PackageCategory::TEXTURE, "/D2/Materials/Decals/Blood003_d.png"},
                {FileType::TEXTURE_SKYBOX, PackageCategory::TEXTURE, "/EE/Materials/Defaults/Textures/Default_y.png"},
                {FileType::TEXTURE_POSTPROCESS, PackageCategory::TEXTURE, "/EE/Materials/Defaults/Textures/Default_v.png"},
                {FileType::TEXTURE_CUBEMAP_1, PackageCategory::TEXTURE, "/D2/Materials/CubeMaps/CC_cube0.png"},
                {FileType::TEXTURE_NORMALMAP, PackageCategory::TEXTURE, "/D2/Weapons/Upgrades/ACOG_n.png"},
            }
        },
        {
            Game::STARTREK,
            {
                {FileType::ANIMATION, PackageCategory::MISC, "/ST/Objects/Vulcan/Lab/VulcanLabsDoorClose_anim.fbx"},
                {FileType::AUDIO_OLD, PackageCategory::MISC, "/ST/Music/LevelMusic/CymbalEndingTrials"},
                {FileType::AUDIO, PackageCategory::MISC, "/Tests/Scripts/TestSound.wav"},
                {FileType::LEVEL, PackageCategory::ANIM_RETARGET, "/ST/Levels/Prefabs/VulcanPrefabs/RAID.level"},
                {FileType::MATERIAL, PackageCategory::MISC, "/ST/Characters/Starfleet/Badges/BadgeSpiral"},
                {FileType::MODEL_STATIC, PackageCategory::MISC, "/ST/Weapons/Gorn/GornAutogun/GornAutoGun.fbx"},
                {FileType::MODEL_LEVEL1, PackageCategory::MISC, "/ST/Levels/VerticalSlice/0_d.obj"},
                {FileType::MODEL_TERRAIN, PackageCategory::MISC, "/ST/Levels/GornFlashback/MindMeldPart2/TerrainT.tmesh"},
                {FileType::MODEL_RIGGED, PackageCategory::MISC, "/ST/Characters/Tmar/TmarFace_skel.fbx"},
                {FileType::SWF, PackageCategory::ANIM_RETARGET, "/ST/Interface/RevealMenu.swf"},
                {FileType::TEXTURE_1, PackageCategory::TEXTURE, "/ST/Weapons/Gorn/Mine/GornMine_d.png"},
                {FileType::TEXTURE_SKYBOX, PackageCategory::TEXTURE, "/EE/Materials/Defaults/Textures/Default_y.png"},
                {FileType::TEXTURE_POSTPROCESS, PackageCategory::TEXTURE, "/EE/Materials/Defaults/Textures/Default_v.png"},
                {FileType::TEXTURE_CUBEMAP_1, PackageCategory::TEXTURE, "/ST/Materials/Cubemaps/Dark_cube0.png"},
                {FileType::TEXTURE_NORMALMAP, PackageCategory::TEXTURE, "/ST/Characters/Scotty/ScottyHead_n.png"},
            }
        },
        {
            Game::KEYSTONE,
            {
                {FileType::ANIMATION, PackageCategory::MISC, "/Keystone/Animations/Turrets/RayGunTurret/Death_anim.fbx"},
                {FileType::AUDIO_OLD, PackageCategory::MISC, "/Keystone/Sounds/Weapons/Colony/RayGun/ColnyRayGunAltFullyCharged"},
                {FileType::AUDIO, PackageCategory::MISC, "/Keystone/Music/DynamicMusic/MainMenu/KeystoneMenuOnePercC.wav"},
                {FileType::ICON, PackageCategory::MISC, "/EE/Editor/Toolbars/Back.ico"},
                {FileType::LEVEL, PackageCategory::ANIM_RETARGET, "/Keystone/Levels/Dioramas/Ray/RayA."},
                {FileType::MATERIAL, PackageCategory::MISC, "/Keystone/Materials/CopyHudCardsPortraitMaterial"},
                {FileType::VERTEXCOLOR, PackageCategory::MISC, "/Keystone/Objects/Carythian/Structural/CaryMariditeMountainAvc.vc"},
                {FileType::MODEL_STATIC, PackageCategory::MISC, "/Keystone/Objects/Colony/Props/Lander.fbx"},
                {FileType::MODEL_LEVEL1, PackageCategory::MISC, "/Keystone/Levels/MainMenu/0_c.fbx"},
                {FileType::MODEL_TERRAIN, PackageCategory::MISC, "/Keystone/Levels/Dioramas/Bristle/BristleA/TerrainD.tmesh"},
                {FileType::MODEL_RIGGED, PackageCategory::MISC, "/Keystone/Characters/Male/Dread/Dread_skel.fbx"},
                {FileType::SHADER, PackageCategory::SHADER_PERMUTATION, "/EE/Shaders/PBRFill/0_p.hlsl"},
                {FileType::SWF, PackageCategory::ANIM_RETARGET, "/Keystone/Menus/MainMenu.swf"},
                {FileType::TEXTURE_1, PackageCategory::TEXTURE, "/Keystone/Characters/BodyParts/Base_d.png"},
                {FileType::TEXTURE_2, PackageCategory::TEXTURE, "/Temp/FontCache/Ksavant_18/F_ja_1_f.png"},
                {FileType::TEXTURE_ROUGHNESS, PackageCategory::TEXTURE, "/Keystone/Objects/Charms/CharmNauticaPearl_r.png"},
                {FileType::TEXTURE_SKYBOX, PackageCategory::TEXTURE, "/EE/Materials/Defaults/Textures/Default_y.png"},
                {FileType::TEXTURE_POSTPROCESS, PackageCategory::TEXTURE, "/EE/Materials/Defaults/Textures/Default_v.png"},
                {FileType::TEXTURE_CUBEMAP_1, PackageCategory::TEXTURE, "/EE/Materials/Basic/ShineBlue_cube0.png"},
                {FileType::TEXTURE_CUBEMAP_PARTIAL, PackageCategory::TEXTURE, "/Keystone/Levels/MainMenu/0_pcube0.png"},
                {FileType::TEXTURE_NORMALMAP, PackageCategory::TEXTURE, "/Keystone/CardSet/Niia/Weapon/DemonBow/DemonBow_n.png"},
                {FileType::TEXTURE_PACKMAP, PackageCategory::TEXTURE, "/EE/Materials/Defaults/NeutralPackMap"},
                {FileType::TEXTURE_DETAILSPACK, PackageCategory::TEXTURE, "/Keystone/Objects/Western/Terrain/WestDirtRockyAPack"},
            }
        },
        {
            Game::WARFRAME_PE,
            {
                {FileType::ANIMATION, PackageCategory::MISC, "/Lotus/Animations/Tenno/Melee/Staff/GroundHit_anim.fbx"},
                {FileType::AUDIO, PackageCategory::MISC, "/Lotus/Sounds/UI/HUD/HudGearSlideIn.wav"},
                {FileType::BINK2, PackageCategory::VIDEO_TEXTURE, "/Lotus/Interface/AbilityVideos/ExcaliburPower1.bk2"},
                {FileType::ICON, PackageCategory::MISC, "/EE/Editor/Darkitect/Icons/Terrain.ico"},
                {FileType::LANDSCAPE, PackageCategory::MISC, "/Lotus/Levels/CivilianHubs/VenusLandscape/0.lndscp"},
                {FileType::LEVEL, PackageCategory::ANIM_RETARGET, "/Lotus/Levels/Episodes/Tutorial.level"},
                {FileType::MATERIAL, PackageCategory::MISC, "/Lotus/Characters/Tenno/Excalibur/ExcaliburPrime"},
                {FileType::MATERIAL_HLM, PackageCategory::MISC, "/Lotus/Objects/Ostron/HLOD/Watchtower_hlod.hlm"},
                {FileType::VERTEXCOLOR, PackageCategory::MISC, "/Lotus/Objects/Orokin/VertexColor/OroTallArchwayAOpenAVCb.vc"},
                {FileType::MODEL_STATIC, PackageCategory::MISC, "/Lotus/Objects/Grineer/Props/CmpCap.fbx"},
                {FileType::MODEL_LEVEL1, PackageCategory::MISC, "/Lotus/Levels/Episodes/VaultKey/0_c.fbx"},
                {FileType::MODEL_LEVEL2, PackageCategory::MISC, "/Lotus/Levels/Cinematics/NewWarIntro/NewWarStageTwo/0_c.fbx"},
                {FileType::MODEL_TERRAIN, PackageCategory::MISC, "/Lotus/Levels/GrineerSettlement/CmpSpawn01/TerrainA.tmesh"},
                {FileType::MODEL_RIGGED, PackageCategory::MISC, "/Lotus/Characters/Tenno/Excalibur/Excalibur_skel.fbx"},
                {FileType::MODEL_PACKED, PackageCategory::MISC, "/Lotus/Objects/Natural/Vegetation/PatchMesh/GrassPatchMeshB"},
                {FileType::MODEL_DCM_HLOD, PackageCategory::MISC, "/Lotus/Objects/Ostron/HLOD/Watchtower_hlod.fbx"},
                {FileType::SHADER, PackageCategory::SHADER_PERMUTATION, "/EE/Shaders/AbsentMipmaps/0_p.hlsl"},
                {FileType::SWF, PackageCategory::ANIM_RETARGET, "/Lotus/Interface/Bumper.swf"},
                {FileType::TEXTURE_1, PackageCategory::TEXTURE, "/EE/Materials/Defaults/Textures/Default_d.png"},
                {FileType::TEXTURE_2, PackageCategory::TEXTURE, "/Lotus/Levels/Outpost/AmbulasBossBattle/TerrainJ_pm.png"},
                {FileType::TEXTURE_3, PackageCategory::TEXTURE, "/Lotus/Objects/Natural/Skybox/CivilianHubs/CivHubAntennaIMP01a_in.png"},
                {FileType::TEXTURE_ROUGHNESS, PackageCategory::TEXTURE, "/Lotus/Weapons/Tenno/LongGuns/PrimeSoma/PrimeSoma_r.png"},
                {FileType::TEXTURE_LIGHTMAP_1, PackageCategory::TEXTURE, "/Lotus/Levels/CivilianHubs/VenusLandscape/Landscape0/T0u0.lchm"}, // Might need different one
                {FileType::TEXTURE_SKYBOX, PackageCategory::TEXTURE, "/EE/Materials/Defaults/Textures/Default_y.png"},
                {FileType::TEXTURE_POSTPROCESS, PackageCategory::TEXTURE, "/EE/Materials/Defaults/Textures/Default_v.png"},
                {FileType::TEXTURE_CUBEMAP_1, PackageCategory::TEXTURE, "/Lotus/Materials/Cubemaps/OrokinA_cube0.png"},
                {FileType::TEXTURE_CUBEMAP_2, PackageCategory::TEXTURE, "/EE/Materials/Util/PerlinNoiseRGBA_vn.tga"},
                {FileType::TEXTURE_CUBEMAP_PARTIAL, PackageCategory::TEXTURE, "/EE/Materials/Defaults/Textures/HDRDefaultCube_pcube0.png"},
                {FileType::TEXTURE_NORMALMAP, PackageCategory::TEXTURE, "/EE/Materials/Defaults/Textures/Default_n.png"},
                {FileType::TEXTURE_PACKMAP, PackageCategory::TEXTURE, "/EE/Materials/Defaults/NeutralPackMap"},
                {FileType::TEXTURE_LANDSCAPE, PackageCategory::TEXTURE, "/Lotus/Objects/Ostron/Natural/Terrain/TerrainPMOSTBeachStone"},
                {FileType::TEXTURE_DETAILSPACK, PackageCategory::TEXTURE, "/Lotus/Objects/Corpus/Structural/CrpStructuralStampPackMap"},
            }
        },
        {
            Game::WARFRAME,
            {
                {FileType::ANIMATION, PackageCategory::MISC, "/Lotus/Animations/Tenno/Melee/Staff/GroundHit_anim.fbx"},
                {FileType::AUDIO, PackageCategory::MISC, "/Lotus/Sounds/UI/HUD/HudGearSlideIn.wav"},
                {FileType::BINK2, PackageCategory::VIDEO_TEXTURE, "/Lotus/Interface/AbilityVideos/ExcaliburPower1.bk2"},
                {FileType::ICON, PackageCategory::MISC, "/EE/Editor/Darkitect/Icons/Terrain.ico"},
                {FileType::LANDSCAPE, PackageCategory::MISC, "/Lotus/Levels/CivilianHubs/VenusLandscape/0.lndscp"},
                {FileType::LEVEL, PackageCategory::ANIM_RETARGET, "/Lotus/Levels/Episodes/Tutorial.level"},
                {FileType::LEVEL_STATIC, PackageCategory::ANIM_RETARGET, "/Lotus/Levels/1999/ObjTempleDefense/0.static"},
                {FileType::MATERIAL, PackageCategory::MISC, "/Lotus/Characters/Tenno/Excalibur/ExcaliburPrime"},
                {FileType::MATERIAL_HLM, PackageCategory::MISC, "/Lotus/Objects/Ostron/HLOD/Watchtower_hlod.hlm"},
                {FileType::VERTEXCOLOR, PackageCategory::MISC, "/Lotus/Objects/Orokin/VertexColor/OroTallArchwayAOpenAVCb.vc"},
                {FileType::MODEL_STATIC, PackageCategory::MISC, "/Lotus/Objects/Grineer/Props/CmpCap.fbx"},
                {FileType::MODEL_LEVEL1, PackageCategory::MISC, "/Lotus/Levels/Episodes/VaultKey/0_c.fbx"},
                {FileType::MODEL_LEVEL2, PackageCategory::MISC, "/Lotus/Levels/Cinematics/NewWarIntro/NewWarStageTwo/0_c.fbx"},
                {FileType::MODEL_TERRAIN, PackageCategory::MISC, "/Lotus/Levels/GrineerSettlement/CmpSpawn01/TerrainA.tmesh"},
                {FileType::MODEL_RIGGED, PackageCategory::MISC, "/Lotus/Characters/Tenno/Excalibur/Excalibur_skel.fbx"},
                {FileType::MODEL_PACKED, PackageCategory::MISC, "/Lotus/Objects/Natural/Vegetation/PatchMesh/GrassPatchMeshB"},
                {FileType::MODEL_DCM_HLOD, PackageCategory::MISC, "/Lotus/Objects/Ostron/HLOD/Watchtower_hlod.fbx"},
                {FileType::SHADER, PackageCategory::SHADER_PERMUTATION, "/EE/Shaders/AbsentMipmaps/0_p.hlsl"},
                {FileType::SWF, PackageCategory::ANIM_RETARGET, "/Lotus/Interface/Bumper.swf"},
                {FileType::TEXTURE_1, PackageCategory::TEXTURE, "/EE/Materials/Defaults/Textures/Default_d.png"},
                {FileType::TEXTURE_2, PackageCategory::TEXTURE, "/Lotus/Objects/Ostron/Natural/Trees/OstSmallTreeYellow_id.png"},
                {FileType::TEXTURE_3, PackageCategory::TEXTURE, "/Lotus/Objects/Natural/Skybox/CivilianHubs/CivHubAntennaIMP01a_in.png"},
                {FileType::TEXTURE_ROUGHNESS, PackageCategory::TEXTURE, "/Lotus/Weapons/Tenno/LongGuns/PrimeSoma/PrimeSoma_r.png"},
                {FileType::TEXTURE_SKYBOX, PackageCategory::TEXTURE, "/EE/Materials/Defaults/Textures/Default_y.png"},
                {FileType::TEXTURE_POSTPROCESS, PackageCategory::TEXTURE, "/EE/Materials/Defaults/Textures/Default_v.png"},
                {FileType::TEXTURE_CUBEMAP_1, PackageCategory::TEXTURE, "/Lotus/Materials/Cubemaps/OrokinA_cube0.png"},
                {FileType::TEXTURE_CUBEMAP_2, PackageCategory::TEXTURE, "/EE/Materials/Util/PerlinNoiseRGBA_vn.tga"},
                {FileType::TEXTURE_CUBEMAP_PARTIAL, PackageCategory::TEXTURE, "/EE/Materials/Defaults/Textures/HDRDefaultCube_pcube0.png"},
                {FileType::TEXTURE_NORMALMAP, PackageCategory::TEXTURE, "/EE/Materials/Defaults/Textures/Default_n.png"},
                {FileType::TEXTURE_PACKMAP, PackageCategory::TEXTURE, "/EE/Materials/Defaults/NeutralPackMap"},
                {FileType::TEXTURE_LANDSCAPE, PackageCategory::TEXTURE, "/Lotus/Objects/Ostron/Natural/Terrain/TerrainPMOSTBeachStone"},
                {FileType::TEXTURE_DETAILSPACK, PackageCategory::TEXTURE, "/Lotus/Objects/Corpus/Structural/CrpStructuralStampPackMap"},
                {FileType::TEXTURE_FVL, PackageCategory::TEXTURE, "/Lotus/Levels/Hub/TennoJunctionRelay/0_fvl.raw"},
                {FileType::TEXTURE_VRGB, PackageCategory::TEXTURE, "/Lotus/Levels/Hub/PlayerShipInteriorOrbiter/0_v.raw"},
                {FileType::TEXTURE_ARRAY, PackageCategory::TEXTURE, "/Lotus/Objects/Duviri/Natural/LandscapeMaterials/DuvxMatIDArrayDR"},
                {FileType::TEXTURE_LIGHTMAP_1, PackageCategory::LIGHT_MAP, "/Lotus/Levels/CivilianHubs/VenusLandscape/Landscape0/T0u0.lchm"},
                {FileType::LIGHTMAP_1, PackageCategory::LIGHT_MAP, "/EE/Materials/Defaults/Textures/BlackSplat.lcsm"},
                {FileType::LIGHTMAP_2, PackageCategory::LIGHT_MAP, "/Lotus/Levels/CivilianHubs/PoeRemaster/TerrainZone8_cmm.png"},
                {FileType::LIGHTMAP_CUBEMAP_PARTIAL, PackageCategory::LIGHT_MAP, "/EE/Materials/Defaults/Textures/HDRDefaultCube_pcube0.png"},
                {FileType::LIGHTMAP_CUBEMAP_SM, PackageCategory::LIGHT_MAP, "/Lotus/Levels/SentientDevourer/ConShortCorner01/3_smcube0.png"},
                {FileType::LIGHTMAP_FVL, PackageCategory::LIGHT_MAP, "/Lotus/Levels/Hub/TennoJunctionRelay/0_fvl.raw"},
                {FileType::LIGHTMAP_VRGB, PackageCategory::LIGHT_MAP, "/Lotus/Levels/Hub/PlayerShipInteriorOrbiter/0_v.raw"},
                {FileType::LIGHTMAP_HDR, PackageCategory::LIGHT_MAP, "/Lotus/Levels/Episodes/VaultKey/0_cross.hdr"},
            }
        },
        {
            Game::SOULFRAME,
            {
                {FileType::ANIMATION, PackageCategory::MISC, "/SF/Fx/Abilities/Ward/HealthTotem/HealthTotem_anim.fbx"},
                {FileType::AUDIO, PackageCategory::MISC, "/SF/Sounds/Animals/Floppet/Vocals/FloppetMiscSqueaksA.wav"},
                {FileType::LANDSCAPE, PackageCategory::MISC, "/SF/Levels/MidrathRedux/0.lndscp"},
                {FileType::LEVEL, PackageCategory::ANIM_RETARGET, "/SF/Levels/Portraits/Avakot.level"},
                {FileType::LEVEL_STATIC, PackageCategory::ANIM_RETARGET, "/SF/Levels/MidrathRedux/0.static"},
                {FileType::LEVEL_T, PackageCategory::ANIM_RETARGET, "/SF/Levels/MidrathRedux/0.tlevel"},
                {FileType::MATERIAL, PackageCategory::MISC, "/SF/Characters/Verminia/VerminiaBody"},
                {FileType::MATERIAL_HLM, PackageCategory::MISC, "/SF/Levels/MidrathRedux/L10L0u0v0g1_hlod.hlm"},
                {FileType::VERTEXCOLOR, PackageCategory::MISC, "/SF/Objects/Dendrit/Structures/Village/LightHouseAuxa.vc"},
                {FileType::MODEL_STATIC, PackageCategory::MISC, "/SF/Objects/Dendrit/Props/DendritBirdFeeder/DendritBirdFeederB.fbx"},
                {FileType::MODEL_LEVEL1, PackageCategory::MISC, "/SF/Levels/Portraits/Avakot/0_c.fbx"},
                {FileType::MODEL_SM, PackageCategory::MISC, "/SF/Levels/MidrathRedux/1_sm.fbx"},
                {FileType::MODEL_TERRAIN, PackageCategory::MISC, "/SF/Levels/MidrathRedux/TerrainA.tmesh"},
                {FileType::MODEL_RIGGED, PackageCategory::MISC, "/SF/Characters/Grandfather/Grandfather_skel.fbx"},
                {FileType::MODEL_PACKED, PackageCategory::MISC, "/SF/Objects/Natural/Plants/Ferns/PatchNettles"},
                {FileType::MODEL_DCM_HLOD, PackageCategory::MISC, "/SF/Objects/Natural/Trees/Redbud/RedBud_dcm.fbx"},
                {FileType::SHADER, PackageCategory::SHADER_PERMUTATION, "/EE/Shaders/Deferred/CharacterPBRDetailDeferred/0_p.hlsl"},
                {FileType::SWF, PackageCategory::ANIM_RETARGET, "/SF/Interface/Codex.swf"},
                {FileType::TEXTURE_1, PackageCategory::TEXTURE, "/SF/Objects/Dendrit/Props/Materials/WickerA_d.png"},
                {FileType::TEXTURE_2, PackageCategory::TEXTURE, "/SF/Objects/Natural/Plants/Reeds/Imposter/ReedClusterA_id.png"},
                {FileType::TEXTURE_3, PackageCategory::TEXTURE, "/SF/Objects/Natural/Plants/Reeds/Imposter/ReedClusterA_in.png"},
                {FileType::TEXTURE_ROUGHNESS, PackageCategory::TEXTURE, "/SF/Objects/Dendrit/Props/Materials/HayPiles/HayPileA_r.png"},
                {FileType::TEXTURE_SKYBOX, PackageCategory::TEXTURE, "/EE/Materials/Defaults/Textures/Default_y.png"},
                {FileType::TEXTURE_POSTPROCESS, PackageCategory::TEXTURE, "/EE/Materials/Defaults/Textures/Default_v.png"},
                {FileType::TEXTURE_CUBEMAP_2, PackageCategory::TEXTURE, "/EE/Materials/Util/PerlinNoisePacked_vn.tga"},
                {FileType::TEXTURE_NORMALMAP, PackageCategory::TEXTURE, "/EE/Materials/Defaults/Textures/Blank_n.png"},
                {FileType::TEXTURE_PACKMAP, PackageCategory::TEXTURE, "/EE/Materials/Defaults/NeutralPackMap"},
                {FileType::TEXTURE_LANDSCAPE, PackageCategory::TEXTURE, "/EE/Materials/Basic/PrevizPlasticLightGrey"},
                {FileType::TEXTURE_DETAILSPACK, PackageCategory::TEXTURE, "/SF/Characters/SproutFolk/Male/SproutMalePackmap"},
                {FileType::TEXTURE_LIGHTMAP_1, PackageCategory::LIGHT_MAP, "/SF/Levels/MidrathRedux/Landscape0/PigmentMaps/T2u1_lpm.png"},
                {FileType::LIGHTMAP_1, PackageCategory::LIGHT_MAP, "/SF/Levels/MidrathRedux/13_mm.png"},
                {FileType::LIGHTMAP_2, PackageCategory::LIGHT_MAP, "/SF/Levels/MidrathRedux/L10L0u0v0g19_hlod.hlpm"},
                {FileType::LIGHTMAP_CUBEMAP_SM, PackageCategory::LIGHT_MAP, "/SF/Levels/MidrathRedux/0_smcube0.png"},
                {FileType::LIGHTMAP_VRGB, PackageCategory::LIGHT_MAP, "/SF/Levels/MidrathRedux/4_v.raw"},
                {FileType::LIGHTMAP_HDR, PackageCategory::LIGHT_MAP, "/SF/Levels/MidrathRedux/1_cross.hdr"},
            }
        }
    };
}